export const baseUrl = "http://localhost:8080/users/";
export const RESETALLSTATESACTION = 'RESETALLSTATESACTION';

export const LOADING_DATA = 'LOADING_DATA';
export const LOADING_DONE = 'LOADING_DONE';

export const USERDETAILS = 'USERDETAILS';
export const LOGINFAILED = 'LOGINFAILED';

export const OTPGENERATIONSTARTED = 'OTPGENERATIONSTARTED';
export const OTPGENERATION = 'OTPGENERATION';
export const ERRORGENERATED = 'ERRORGENERATED';

export const CHECKOTPSTARTED = 'CHECKOTPSTARTED';
export const CHECKOTP = 'CHECKOTP';
export const CHECKOTPERROR = 'CHECKOTPERROR';

export const RESETPASSWORDSTARTED = 'RESETPASSWORDSTARTED';
export const RESETPASSWORD= 'RESETPASSWORD';
export const RESETPASSWORDERROR = 'RESETPASSWORDERROR';

export const CHANGEPASSWORDSTARTED = 'CHANGEPASSWORDSTARTED';
export const CHANGEPASSWORD= 'CHANGEPASSWORD';
export const CHANGEPASSWORDERROR = 'CHANGEPASSWORDERROR';

export const UPDATEUSER = 'UPDATEUSER';
export const DELETEUSER = 'DELETEUSER';
export const VIEWUSER = 'VIEWUSER';